# Site settings
title: "Benjamin Kanouse"
description: "Benjamin Kanouse's Resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Benjamin Kanouse"
resume_title:                   "Principal Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "kanobt61@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "716-243-5309"
resume_contact_address:         ""

resume_header_contact_info:     "716-243-5309 • kanobt61@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Experienced Principal Software Engineer with a strong focus on Ruby on Rails, PostgreSQL, and JavaScript. Passionate about clean code, test-driven development, and performance optimization. With over a decade of experience, successfully led teams of up to 20 engineers, driving the design, development, and optimization of large-scale applications. Holding a Master of Science in Computational and Applied Mathematics from the State University of New York College at Buffalo, dedicated to leveraging my technical and leadership skills to deliver innovative solutions and create a meaningful impact.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_open_source:     true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/BenKanouse"
  # resume_twitter_url:           "https://twitter.com/kanobt61"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/benjamin-kanouse-22a7ba74"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://blog.benkanouse.com/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
